import type { ResolvedConfig } from "@/config";

export const GENERATED_HEADER = "<!-- AUTO-GENERATED by agents-compose. DO NOT EDIT. -->";

export interface RenderedSource {
	relativePath: string;
	content: string;
}

export function render(config: ResolvedConfig, sources: RenderedSource[]): string {
	const sections: string[] = [];

	if (config.generatedHeader) {
		sections.push(GENERATED_HEADER);
	}

	for (const source of sources) {
		const lines: string[] = [];
		if (config.sourceComments) {
			lines.push(`<!-- source: ${source.relativePath} -->`);
		}
		if (source.content.length > 0) {
			lines.push(source.content);
		}
		if (lines.length > 0) {
			sections.push(lines.join("\n"));
		}
	}

	return `${sections.join("\n\n")}\n`;
}
